[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.0.1"
